---
# tasks file for destroy
  - name: Gather information about all droplets
    community.digitalocean.digital_ocean_droplet_info:
      oauth_token: "{{ DO_API_TOKEN }}"
      name: code-droplet
    register: droplet
    failed_when: droplet.data | length == 0
    ignore_errors: yes

  - name: test

    block:
    
     - name: Destroy droplet
       community.digitalocean.digital_ocean_droplet:
         state: absent
         oauth_token: "{{ DO_API_TOKEN }}"
         id: "{{ droplet['data'][0]['id'] }}"

    when: droplet['failed'] == false